// MOTOR CONTROL CONSTANTS //
#define FRONT_RIGHT_MOTOR_PIN
#define FRONT_LEFT_MOTOR_PIN
#define BACK_RIGHT_MOTOR_PIN
#define BACK_LEFT_MOTOR_PIN
#define TALON_NEUTRAL_FREQUENCY 1500

// ETHERNET COMMUNICATION CONSTANTS //
#define UDP_PORT         8888
#define DESTINATION_PORT 8888

// SERIAL COMMUNICATION CONSTANTS //
#define BAUDRATE 9600
