// MOTOR CONTROL CONSTANTS //
#define FRONT_RIGHT_MOTOR_PIN
#define FRONT_EFT_MOTOR_PIN
#define BACK_RIGHT_MOTOR_PIN
#define BACK_LEFT_MOTOR_PIN
#define TALON_NEUTRAL_FREQUENCY 1500

// ETHERNET COMMUNICATION CONSTANTS //
const byte MAC_ADDRESS[] = {0xDE, 0xAD, 0xBE, 0xEF, 0xFE, 0xED};
#define UDP_PORT         8888
#define DESTINATION_PORT 8888

